### ISSUE TITLE
Score computation, 

### ISSUE THREAD

**Issue by PaulaAlessio** [bcgsc/biobloom#14]
Hello, 

   I am concerned about the computation of the score in the function: evalSingle (file EvalSeq.h). In line 95, 
     score += 1 - 1 / (2 * streak);
should not be substituted by
     score += 1 - 1.0  / (2.0 * streak);
? 

Otherwise 1/ (2 * streak ) is always 0 since streak is **unsigned**.  

On top of that, I do not understand the presence of "2" in the formula, from the score definition you give in the article. 

Yours sincerely, 

Paula

**Comment by JustinChu** [comment]
This is embarrassingly correct. I need to determine if this has been the case in all our versions and update benchmarking/evaluations accordingly. It may be that our has worked despite this issue, though it does call into question what we publishied in our paper.

Thank you for bringing this to my attention.

**Comment by PaulaAlessio** [comment]
Hello,

   ok, yes, I do not think it will have an outrageous impact on the
results. The only thing is that the way it is written now does not penalize
likely false positive hits. The score gets incremented equally by all kmers
matching the filter (excepting the first in a stretch). But, if the false
positive rate is required to be small, anyway, I would not expect a huge
impact, if one is using the tool. For benchmarking, it might matter...

Yours,

Paula

2017-05-23 0:49 GMT+02:00 Justin Chu <notifications@github.com>:

**Comment by JustinChu** [comment]
It is very an obvious error and yet one of the reasons we didn't see the error I think is because our classification results still seemed fairly robust. Basically, I think if you tried to use the tool you'd find the results still make sense.

We essentially and unintentionally implemented a scoring system that introduces a simple gap/mismatch penalty (similar to SW). We also introduced/moved on to different classification schemes in this branch and testing others for specific purposes like a simple minimum length match classification.

This may be a blessing in disguise as it gives me an excuse to try out and benchmark different classification schemes that I have wanted to for a while.

**Comment by JustinChu** [comment]
To be clear I start by evaluating results for:
```
score += 1.0 - 1.0 / (double(streak) + 1.0);
```
vs the current (accidental) scheme:
```
score += streak == 1 ? 0.5 : 1.0;
```
and any others that seems promising

**Comment by JustinChu** [comment]
Results on simulated (via dwgsim) 1,000,000 human 2x150bp reads and 1,000,000 mouse 2x150bp reads using the 2 methods:
![bbt_compare_mouse_human_0 0075](https://cloud.githubusercontent.com/assets/1156466/26382854/3a6ee258-3fe4-11e7-9d0b-1c2ebefa9675.png)

Bloom filter FPR: 0.0075 (current default), note that this is lower than the FPR in our publication.

Score range tested 0.05 to 0.15

These results suggest Interestingly the current (unintended) method performs better given this genome type and Bloom Filter FPR.

**Comment by JustinChu** [comment]
For good measure the result of using an FPR of 0.02 for the Bloom Filter:

![bbt_compare_mouse_human_0 02](https://cloud.githubusercontent.com/assets/1156466/26384580/3560a408-3fef-11e7-841f-fe95aad1347b.png)

Simple increment is the counts if we simply incremented by 1.0 each time including the first match of the screak.

**Comment by JustinChu** [comment]
At FPR = 0.0625 with ecoli instead of mouse:
![bbt_compare_ecoli_human_0 0625](https://cloud.githubusercontent.com/assets/1156466/26427613/643e5c04-4092-11e7-9999-089b01e41a11.png)

![bbt_scores_0 0625](https://cloud.githubusercontent.com/assets/1156466/26427862/81e0ae5a-4093-11e7-8aaf-3974fdda70c4.png)

Again, the incorrect (original) scoring algorithm doesn't seem significantly different from the intended one. Because there are some pipelines that rely on the score the way it is, the code will remain functionally the same but I will provide the intended scoring algorithm in a version 2.1.*.

I will clean up the code for the current scoring algorithm (remove the pointless parts).

Thanks again for helping me elucidate this discrepancy.

**Comment by PaulaAlessio** [comment]
Hello,

   Thank you very much for the benchmarks. I would have actually expected
the "intended algorithm" to perform slightly better, but it does not seem
to be the case.

Paula

2017-05-25 0:14 GMT+02:00 Justin Chu <notifications@github.com>:
