### ISSUE TITLE
How to create filters for many reference genomes?

### ISSUE THREAD

**Issue by lh12565** [bcgsc/biobloom#38]
Hi,
I want to detect if there is any virus in my sample. I have hundreds of virus reference genomes or sequences. Do I have to build hundreds of filters?
I have two other questions. one is the difference between "shared" and "multiMatch" in the summary file, and the other is when I build a filter of human reference genome, there is some information as below:

```{bash}
The ratio between redundant k-mers and unique k-mers is approximately: 0.300735
Consider checking your files for duplicate sequences and adjusting them accordingly.
High redundancy will cause filter sizes used overestimated, potentially resulting in a larger than needed filter.
Alternatively you can set the number of elements wanted in the filter with (-n) and ignore this message
```

Can this information be ignored?
Thanks!

**Comment by JustinChu** [comment]
If you simply want to classify to a set of genomes as one target you can build the filter with a multi fasta file or list a set of files when creating filters. e.g. 
```{bash}
biobloommaker -p viralFilter virus_*.fa
biobloommaker -p humanFilter human.fa
biobloomcategorizer -f "viralFilter.bf humanFilter.bf" reads.fa
```

All viruses would classify to the one filter viralFilter listed.

If you have more than 100 targets you shouldn't use normal BBT, but could try the [multi-index variant](https://github.com/bcgsc/biobloom/blob/master/Doc/MultiIndex.md). In this case you would built 1 filter for multiple targets. It will classify to seperate targets rather than one viral target. Note that it doesn't exactly work too well if there is a lot of sequence redundancy in your targets, however it may be fine for viruses since they have high mutation rates.

As for message produced, it is mostly innoculous. Having high redudancy simply means we are allocating more space than needed for the number of elements because the file has a lot of repeatetive sequence. It won't make the results worse. When it is really high (>2), it indicates that you may have listed the same sequences more than once in your input.

**Comment by lh12565** [comment]
Hi Justin Chu,
In multi-index variant, you say "it may be helpful to add human sequences as they will reduce the FPR of the viral sequences in the filter". Do you mean build a filter for both human sequences and viruses, such as :

```{bash}
util/genRV.sh viral.fa human.fa
./biobloommimaker -p filterName -S "011110111000000...." viral.fa human.fa
./biobloommicategorizer -f filterName.bf viral.fa human.fa
```

But I think I don't need to separate human.fa, could I use biobloomcategorizer to deal with human.fa and biobloommicategorizer for viral.fa, such as:

```{bash}
./biobloommaker –p input human.fasta
./biobloomcategorizer -e –p /output/prefix –f "human.bf" human.fa

util/genRV.sh viral.fa
./biobloommimaker -p filterName -S "011110111000000...." viral.fa
./biobloommicategorizer -f filterName.bf viral.fa
```

Thanks!

**Comment by JustinChu** [comment]
Depending on your data and needs, I think both methods are fine. The difference is that you can do the classification in a single pass of both human and viral sequences. The second case allow you to filter human-like reads first, even if the human reads look more like viral sequences to proritize false positives human-origin hits.

I think the comment you quoted in the manual could be worder better and might be a bit confusing, but in essense it is another memory trade off to achieve higher specifity and sensitivity. This can be achieved by adding more sequences to the filter (like human seqeunces) but can be in other ways as well. For example, it may help to in the second example you stated to decrease the `-b` parameter (decreasing the occupancy) from 0.5 to 0.25 or 0.1 to achieve a similar effect.
