### ISSUE TITLE
False positive

### ISSUE THREAD

**Issue by adrienlemeur** [bcgsc/biobloom#84]
Hello, 

It is a strange idea, but I would like to use the false positive rate at my advantage. I want to remove reads matching a set of sequences in several FASTQ files, but I don't want to remove all of them.
Do you think that if I set the false positive threshold to something like 10% it will pervasively remove some of reads like I intended ? In the end, after aligning to my genome I want to have specific low coverage regions ~ 10%. 

Thank you,
Adrien

**Comment by lcoombe** [comment]
Hi @adrienlemeur,

That is an interesting thought. 
Just to make sure we're on the same page about what you're looking to achieve - You have a set of reads that you are hoping to filter. You will load the target sequences that you'd like to remove into Bloom filters, then run BBT to filter out reads that hit to those Bloom filters, but you don't want to remove _all_ of the hitting reads?

If I'm interpreting right, there are a couple of things to think about. First, if you are trying to filter out only some of the reads that hit to the Bloom filter, raising the false positive rate may not have the impact that you want - ie. you may have hits to the Bloom filter from reads that are in non-target regions of your genome, meaning that you'll reduce the coverage in those genome loci. With a higher false positive rate, I would still expect the reads from your target regions to be filtered. Also, it's hard to have guarantees about percentages, since BBT works off a calculated score (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4816029/) , so there is more to consider than just the FPR.

Again, if I'm understanding correctly that you want to retain (not filter out all) some of the Bloom filter target sequences, you could run BBT, then just add back a % of the filtered reads to your read set? That would give you more control over how much of the 'contaminating/filtered' sequence you add back.

I hope that helps - thank you for your interest in BBT!
Lauren

**Comment by adrienlemeur** [comment]
Yes, this is what I wanted to do !

Everything you said happened :D ; in the end I had the same mean coverage among the regions I wanted to deplete than the other regions of my genome. So I resigned to 1) extract the regions I wanted with BBT and a low FP 2) subsample the reads to the desired % with bbmap 3) re-added the reads to the mix.

Thank for your answer,
Adrien

**Comment by lcoombe** [comment]
That sounds like a good approach! Glad you worked it out :)
